language: rust

notifications:
    email:
        on_success: never
        on_failure: always

env:
    global:
        - secure: kU2PHgkMed4zn1YskwzKj5M/bRGz5VOkePZMwv5cmJ8wjgm+/U6lggvCIcpSJOAEF0QzZ9wFfKjhPYwI8lNKRMC0KU6mbYBh/HOiGC4Ym1HZa9mV//rXfn28DFywc5MW3qvWBRcAfl9U8hYcgsNMz3YIeKUFm3Ju7tqYrs3f38U=

script:
    - cargo build
    - cargo test
    - cargo doc

after_script:
    - cd target && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
