[package]

name = "spinlock"
version = "0.1.1"
authors = [ "Mathijs van de Nes <git@mathijs.vd-nes.nl>" ]
license = "MIT"
repository = "https://github.com/mvdnes/spinlock-rs.git"
documentation = "https://mvdnes.github.io/spinlock-rs/"
description = """
A simple spinlock.
It may contain data,
is usable without std
and there is a static initializer available.
"""
