[package]

name = "spinlock"
version = "0.1.2"
authors = [ "Mathijs van de Nes <git@mathijs.vd-nes.nl>" ]
license = "MIT"
repository = "https://github.com/mvdnes/spinlock-rs.git"
description = """
DEPRECATED!
Use crate `spin` instead.

A simple spinlock.
It may contain data,
is usable without std
and there is a static initializer available.
"""
